// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int pkg/e/apiserver.go"; DO NOT EDIT.

package e

// init register error codes defines in this source code to `github.com/marmotedu/errors`
func init() {
	register(SUCCESS, 200, "OK")
	register(ERROR, 500, "Fail")
	register(INVALID_PARAMS, 400, "Request parameter error")
	register(ERROR_EXIST_TAG, 401, "The label already exists")
	register(ERROR_NOT_EXIST_TAG, 401, "The label does not exist")
	register(ERROR_NOT_EXIST_ARTICLE, 401, "The article does not exist")
	register(ERROR_AUTH_CHECK_TOKEN_FAIL, 403, "Token鉴权失败")
	register(ERROR_AUTH_CHECK_TOKEN_TIMEOUT, 403, "Token已超时")
	register(ERROR_AUTH_TOKEN, 403, "Token生成失败")
	register(ERROR_AUTH, 403, "Token错误")
	register(VALIDARION_ERRORS, 403, "Illegal field")
}
