definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Tag:
    properties:
      created_by:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
      updatedAt:
        type: string
    type: object
  paginate.Query:
    properties:
      all_data:
        type: boolean
      order:
        default: desc
        description: 排序参数(desc:倒序、asc：正序)
        enum:
        - desc
        - asc
        type: string
      order_by:
        default: id
        description: 排序对象
        type: string
      page:
        default: 1
        description: 页码
        minimum: -1
        type: integer
      page_size:
        default: 20
        description: 每页大小(最大1000条)
        maximum: 1000
        minimum: -1
        type: integer
      search:
        description: 模糊查询
        type: string
    type: object
  render.HTTPError:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: Service internal error
        type: string
    type: object
  render.HTTPSuccess:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: request ok 200
        type: string
    type: object
  render.PaginateData:
    properties:
      items:
        type: object
      paginate:
        $ref: '#/definitions/render.PaginateInfo'
    type: object
  render.PaginateInfo:
    properties:
      page:
        description: 页数
        type: integer
      page_size:
        description: 每页数据量
        type: integer
      total:
        description: 数据总数
        type: integer
    type: object
  render.PaginateResult:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        $ref: '#/definitions/render.PaginateData'
        description: 返回内容
      msg:
        description: 请求结果
        type: string
    type: object
  request.CreateTagRequest:
    properties:
      created_by:
        type: string
      name:
        type: string
      state:
        type: integer
    required:
    - created_by
    - name
    type: object
  request.UpdateTagRequest:
    properties:
      id:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
  response.CreateTagResponse:
    properties:
      created_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  response.GetTagResponse:
    properties:
      created_by:
        type: string
      id:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  response.UpdateTagResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/tag:
    get:
      consumes:
      - application/json
      description: List all tag
      parameters:
      - description: 分页查询对象
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/paginate.Query'
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            allOf:
            - $ref: '#/definitions/render.PaginateResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Tag'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: List all tag - 返回所有 tag 数据.
      tags:
      - tag
    patch:
      consumes:
      - application/json
      description: Update an article tag
      parameters:
      - description: Update article tag
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/request.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UpdateTagResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: Update a tag - 更新文章标签
      tags:
      - tag
    post:
      consumes:
      - application/json
      description: create an article tag
      parameters:
      - description: Add article tag
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/request.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateTagResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: create a tag - 创建一个文章标签
      tags:
      - tag
  /api/v1/tag/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an article tag
      parameters:
      - description: Tag ID
        format: uint
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/render.HTTPSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: Delete a tag - 删除文章标签
      tags:
      - tag
    get:
      consumes:
      - application/json
      description: Get an article tag (获取单个文章标签)
      parameters:
      - description: Tag ID
        format: uint
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetTagResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: Get a tag - 获取单个文章标签
      tags:
      - tag
swagger: "2.0"
