definitions:
  render.HTTPError:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: Service internal error
        type: string
    type: object
  render.HTTPSuccess:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: request ok 200
        type: string
    type: object
  request.CreateTagRequest:
    properties:
      created_by:
        type: string
      name:
        type: string
      state:
        type: integer
    required:
    - created_by
    - name
    type: object
  request.UpdateTagRequest:
    properties:
      id:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
  response.CreateTagResponse:
    properties:
      created_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  response.GetTagResponse:
    properties:
      created_by:
        type: string
      id:
        type: integer
      modified_by:
        type: string
      name:
        type: string
      state:
        type: integer
    type: object
  response.UpdateTagResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/tag:
    patch:
      consumes:
      - application/json
      description: Update an article tag
      parameters:
      - description: Update article tag
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/request.UpdateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UpdateTagResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: Update a tag - 更新文章标签
      tags:
      - tag
    post:
      consumes:
      - application/json
      description: create an article tag
      parameters:
      - description: Add article tag
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/request.CreateTagRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateTagResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: create a tag - 创建一个文章标签
      tags:
      - tag
  /api/v1/tag/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an article tag
      parameters:
      - description: Tag ID
        format: uint
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/render.HTTPSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: Delete a tag - 删除文章标签
      tags:
      - tag
    get:
      consumes:
      - application/json
      description: Get an article tag (获取单个文章标签)
      parameters:
      - description: Tag ID
        format: uint
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.GetTagResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/render.HTTPError'
      summary: Get a tag - 获取单个文章标签
      tags:
      - tag
swagger: "2.0"
